//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyllabusPlusSchedulerService.UserManagement {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationInfo", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class AuthenticationInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode {
            get {
                return this.AuthCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthCodeField, value) != true)) {
                    this.AuthCodeField = value;
                    this.RaisePropertyChanged("AuthCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey {
            get {
                return this.UserKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.UserKeyField, value) != true)) {
                    this.UserKeyField = value;
                    this.RaisePropertyChanged("UserKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EmailSessionNotificationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid[] GroupMembershipsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SyllabusPlusSchedulerService.UserManagement.SystemRole SystemRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserBioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserSettingsUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EmailSessionNotifications {
            get {
                return this.EmailSessionNotificationsField;
            }
            set {
                if ((this.EmailSessionNotificationsField.Equals(value) != true)) {
                    this.EmailSessionNotificationsField = value;
                    this.RaisePropertyChanged("EmailSessionNotifications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] GroupMemberships {
            get {
                return this.GroupMembershipsField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupMembershipsField, value) != true)) {
                    this.GroupMembershipsField = value;
                    this.RaisePropertyChanged("GroupMemberships");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyllabusPlusSchedulerService.UserManagement.SystemRole SystemRole {
            get {
                return this.SystemRoleField;
            }
            set {
                if ((this.SystemRoleField.Equals(value) != true)) {
                    this.SystemRoleField = value;
                    this.RaisePropertyChanged("SystemRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserBio {
            get {
                return this.UserBioField;
            }
            set {
                if ((object.ReferenceEquals(this.UserBioField, value) != true)) {
                    this.UserBioField = value;
                    this.RaisePropertyChanged("UserBio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey {
            get {
                return this.UserKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.UserKeyField, value) != true)) {
                    this.UserKeyField = value;
                    this.RaisePropertyChanged("UserKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserSettingsUrl {
            get {
                return this.UserSettingsUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSettingsUrlField, value) != true)) {
                    this.UserSettingsUrlField = value;
                    this.RaisePropertyChanged("UserSettingsUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemRole", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum SystemRole : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Videographer = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListUsersRequest", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class ListUsersRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SyllabusPlusSchedulerService.UserManagement.Pagination PaginationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SyllabusPlusSchedulerService.UserManagement.UserSortField SortByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SortIncreasingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyllabusPlusSchedulerService.UserManagement.Pagination Pagination {
            get {
                return this.PaginationField;
            }
            set {
                if ((object.ReferenceEquals(this.PaginationField, value) != true)) {
                    this.PaginationField = value;
                    this.RaisePropertyChanged("Pagination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyllabusPlusSchedulerService.UserManagement.UserSortField SortBy {
            get {
                return this.SortByField;
            }
            set {
                if ((this.SortByField.Equals(value) != true)) {
                    this.SortByField = value;
                    this.RaisePropertyChanged("SortBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SortIncreasing {
            get {
                return this.SortIncreasingField;
            }
            set {
                if ((this.SortIncreasingField.Equals(value) != true)) {
                    this.SortIncreasingField = value;
                    this.RaisePropertyChanged("SortIncreasing");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pagination", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class Pagination : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxNumberResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxNumberResults {
            get {
                return this.MaxNumberResultsField;
            }
            set {
                if ((this.MaxNumberResultsField.Equals(value) != true)) {
                    this.MaxNumberResultsField = value;
                    this.RaisePropertyChanged("MaxNumberResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSortField", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum UserSortField : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserKey = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Role = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LastLogOn = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FullName = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListUsersResponse", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class ListUsersResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SyllabusPlusSchedulerService.UserManagement.User[] PagedResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalResultCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyllabusPlusSchedulerService.UserManagement.User[] PagedResults {
            get {
                return this.PagedResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.PagedResultsField, value) != true)) {
                    this.PagedResultsField = value;
                    this.RaisePropertyChanged("PagedResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalResultCount {
            get {
                return this.TotalResultCountField;
            }
            set {
                if ((this.TotalResultCountField.Equals(value) != true)) {
                    this.TotalResultCountField = value;
                    this.RaisePropertyChanged("TotalResultCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class Group : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SyllabusPlusSchedulerService.UserManagement.GroupType GroupTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MembershipProviderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SyllabusPlusSchedulerService.UserManagement.SystemRole SystemRoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyllabusPlusSchedulerService.UserManagement.GroupType GroupType {
            get {
                return this.GroupTypeField;
            }
            set {
                if ((this.GroupTypeField.Equals(value) != true)) {
                    this.GroupTypeField = value;
                    this.RaisePropertyChanged("GroupType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MembershipProviderName {
            get {
                return this.MembershipProviderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MembershipProviderNameField, value) != true)) {
                    this.MembershipProviderNameField = value;
                    this.RaisePropertyChanged("MembershipProviderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyllabusPlusSchedulerService.UserManagement.SystemRole SystemRole {
            get {
                return this.SystemRoleField;
            }
            set {
                if ((this.SystemRoleField.Equals(value) != true)) {
                    this.SystemRoleField = value;
                    this.RaisePropertyChanged("SystemRole");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupType", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum GroupType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ActiveDirectory = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        External = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Internal = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListGroupsResponse", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class ListGroupsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SyllabusPlusSchedulerService.UserManagement.Group[] PagedResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalResultCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SyllabusPlusSchedulerService.UserManagement.Group[] PagedResults {
            get {
                return this.PagedResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.PagedResultsField, value) != true)) {
                    this.PagedResultsField = value;
                    this.RaisePropertyChanged("PagedResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalResultCount {
            get {
                return this.TotalResultCountField;
            }
            set {
                if ((this.TotalResultCountField.Equals(value) != true)) {
                    this.TotalResultCountField = value;
                    this.RaisePropertyChanged("TotalResultCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserManagement.IUserManagement")]
    public interface IUserManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/CreateUser", ReplyAction="http://tempuri.org/IUserManagement/CreateUserResponse")]
        System.Guid CreateUser(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, SyllabusPlusSchedulerService.UserManagement.User user, string initialPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/CreateUser", ReplyAction="http://tempuri.org/IUserManagement/CreateUserResponse")]
        System.Threading.Tasks.Task<System.Guid> CreateUserAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, SyllabusPlusSchedulerService.UserManagement.User user, string initialPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/CreateUsers", ReplyAction="http://tempuri.org/IUserManagement/CreateUsersResponse")]
        SyllabusPlusSchedulerService.UserManagement.User[] CreateUsers(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, SyllabusPlusSchedulerService.UserManagement.User[] users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/CreateUsers", ReplyAction="http://tempuri.org/IUserManagement/CreateUsersResponse")]
        System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.User[]> CreateUsersAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, SyllabusPlusSchedulerService.UserManagement.User[] users);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetUserByKey", ReplyAction="http://tempuri.org/IUserManagement/GetUserByKeyResponse")]
        SyllabusPlusSchedulerService.UserManagement.User GetUserByKey(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string userKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetUserByKey", ReplyAction="http://tempuri.org/IUserManagement/GetUserByKeyResponse")]
        System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.User> GetUserByKeyAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string userKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetUsers", ReplyAction="http://tempuri.org/IUserManagement/GetUsersResponse")]
        SyllabusPlusSchedulerService.UserManagement.User[] GetUsers(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid[] userIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetUsers", ReplyAction="http://tempuri.org/IUserManagement/GetUsersResponse")]
        System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.User[]> GetUsersAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid[] userIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/ListUsers", ReplyAction="http://tempuri.org/IUserManagement/ListUsersResponse")]
        SyllabusPlusSchedulerService.UserManagement.ListUsersResponse ListUsers(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, SyllabusPlusSchedulerService.UserManagement.ListUsersRequest parameters, string searchQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/ListUsers", ReplyAction="http://tempuri.org/IUserManagement/ListUsersResponse")]
        System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.ListUsersResponse> ListUsersAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, SyllabusPlusSchedulerService.UserManagement.ListUsersRequest parameters, string searchQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/UpdateContactInfo", ReplyAction="http://tempuri.org/IUserManagement/UpdateContactInfoResponse")]
        void UpdateContactInfo(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId, string firstName, string lastName, string email, bool sendNotifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/UpdateContactInfo", ReplyAction="http://tempuri.org/IUserManagement/UpdateContactInfoResponse")]
        System.Threading.Tasks.Task UpdateContactInfoAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId, string firstName, string lastName, string email, bool sendNotifications);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/UpdateUserBio", ReplyAction="http://tempuri.org/IUserManagement/UpdateUserBioResponse")]
        void UpdateUserBio(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId, string bio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/UpdateUserBio", ReplyAction="http://tempuri.org/IUserManagement/UpdateUserBioResponse")]
        System.Threading.Tasks.Task UpdateUserBioAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId, string bio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/UpdatePassword", ReplyAction="http://tempuri.org/IUserManagement/UpdatePasswordResponse")]
        void UpdatePassword(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/UpdatePassword", ReplyAction="http://tempuri.org/IUserManagement/UpdatePasswordResponse")]
        System.Threading.Tasks.Task UpdatePasswordAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/ResetPassword", ReplyAction="http://tempuri.org/IUserManagement/ResetPasswordResponse")]
        void ResetPassword(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/ResetPassword", ReplyAction="http://tempuri.org/IUserManagement/ResetPasswordResponse")]
        System.Threading.Tasks.Task ResetPasswordAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/UnlockAccount", ReplyAction="http://tempuri.org/IUserManagement/UnlockAccountResponse")]
        void UnlockAccount(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/UnlockAccount", ReplyAction="http://tempuri.org/IUserManagement/UnlockAccountResponse")]
        System.Threading.Tasks.Task UnlockAccountAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/SetSystemRole", ReplyAction="http://tempuri.org/IUserManagement/SetSystemRoleResponse")]
        void SetSystemRole(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId, SyllabusPlusSchedulerService.UserManagement.SystemRole role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/SetSystemRole", ReplyAction="http://tempuri.org/IUserManagement/SetSystemRoleResponse")]
        System.Threading.Tasks.Task SetSystemRoleAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId, SyllabusPlusSchedulerService.UserManagement.SystemRole role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/DeleteUsers", ReplyAction="http://tempuri.org/IUserManagement/DeleteUsersResponse")]
        void DeleteUsers(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid[] userIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/DeleteUsers", ReplyAction="http://tempuri.org/IUserManagement/DeleteUsersResponse")]
        System.Threading.Tasks.Task DeleteUsersAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid[] userIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/CreateInternalGroup", ReplyAction="http://tempuri.org/IUserManagement/CreateInternalGroupResponse")]
        SyllabusPlusSchedulerService.UserManagement.Group CreateInternalGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string groupName, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/CreateInternalGroup", ReplyAction="http://tempuri.org/IUserManagement/CreateInternalGroupResponse")]
        System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.Group> CreateInternalGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string groupName, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetGroupIsPublic", ReplyAction="http://tempuri.org/IUserManagement/GetGroupIsPublicResponse")]
        bool GetGroupIsPublic(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetGroupIsPublic", ReplyAction="http://tempuri.org/IUserManagement/GetGroupIsPublicResponse")]
        System.Threading.Tasks.Task<bool> GetGroupIsPublicAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/SetGroupIsPublic", ReplyAction="http://tempuri.org/IUserManagement/SetGroupIsPublicResponse")]
        void SetGroupIsPublic(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId, bool isPublic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/SetGroupIsPublic", ReplyAction="http://tempuri.org/IUserManagement/SetGroupIsPublicResponse")]
        System.Threading.Tasks.Task SetGroupIsPublicAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId, bool isPublic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/CreateExternalGroup", ReplyAction="http://tempuri.org/IUserManagement/CreateExternalGroupResponse")]
        SyllabusPlusSchedulerService.UserManagement.Group CreateExternalGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string groupName, string externalProvider, string externalId, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/CreateExternalGroup", ReplyAction="http://tempuri.org/IUserManagement/CreateExternalGroupResponse")]
        System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.Group> CreateExternalGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string groupName, string externalProvider, string externalId, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/AddMembersToInternalGroup", ReplyAction="http://tempuri.org/IUserManagement/AddMembersToInternalGroupResponse")]
        void AddMembersToInternalGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/AddMembersToInternalGroup", ReplyAction="http://tempuri.org/IUserManagement/AddMembersToInternalGroupResponse")]
        System.Threading.Tasks.Task AddMembersToInternalGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/RemoveMembersFromInternalGroup", ReplyAction="http://tempuri.org/IUserManagement/RemoveMembersFromInternalGroupResponse")]
        void RemoveMembersFromInternalGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/RemoveMembersFromInternalGroup", ReplyAction="http://tempuri.org/IUserManagement/RemoveMembersFromInternalGroupResponse")]
        System.Threading.Tasks.Task RemoveMembersFromInternalGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/AddMembersToExternalGroup", ReplyAction="http://tempuri.org/IUserManagement/AddMembersToExternalGroupResponse")]
        void AddMembersToExternalGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string externalProviderName, string externalGroupId, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/AddMembersToExternalGroup", ReplyAction="http://tempuri.org/IUserManagement/AddMembersToExternalGroupResponse")]
        System.Threading.Tasks.Task AddMembersToExternalGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string externalProviderName, string externalGroupId, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/RemoveMembersFromExternalGroup", ReplyAction="http://tempuri.org/IUserManagement/RemoveMembersFromExternalGroupResponse")]
        void RemoveMembersFromExternalGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string externalProviderName, string externalGroupId, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/RemoveMembersFromExternalGroup", ReplyAction="http://tempuri.org/IUserManagement/RemoveMembersFromExternalGroupResponse")]
        System.Threading.Tasks.Task RemoveMembersFromExternalGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string externalProviderName, string externalGroupId, System.Guid[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/SyncExternalUser", ReplyAction="http://tempuri.org/IUserManagement/SyncExternalUserResponse")]
        void SyncExternalUser(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string firstName, string lastName, string email, bool EmailSessionNotifications, string[] externalGroupIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/SyncExternalUser", ReplyAction="http://tempuri.org/IUserManagement/SyncExternalUserResponse")]
        System.Threading.Tasks.Task SyncExternalUserAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string firstName, string lastName, string email, bool EmailSessionNotifications, string[] externalGroupIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/DeleteGroup", ReplyAction="http://tempuri.org/IUserManagement/DeleteGroupResponse")]
        void DeleteGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/DeleteGroup", ReplyAction="http://tempuri.org/IUserManagement/DeleteGroupResponse")]
        System.Threading.Tasks.Task DeleteGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetGroup", ReplyAction="http://tempuri.org/IUserManagement/GetGroupResponse")]
        SyllabusPlusSchedulerService.UserManagement.Group GetGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetGroup", ReplyAction="http://tempuri.org/IUserManagement/GetGroupResponse")]
        System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.Group> GetGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/ListGroups", ReplyAction="http://tempuri.org/IUserManagement/ListGroupsResponse")]
        SyllabusPlusSchedulerService.UserManagement.ListGroupsResponse ListGroups(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, SyllabusPlusSchedulerService.UserManagement.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/ListGroups", ReplyAction="http://tempuri.org/IUserManagement/ListGroupsResponse")]
        System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.ListGroupsResponse> ListGroupsAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, SyllabusPlusSchedulerService.UserManagement.Pagination pagination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetGroupsByName", ReplyAction="http://tempuri.org/IUserManagement/GetGroupsByNameResponse")]
        SyllabusPlusSchedulerService.UserManagement.Group[] GetGroupsByName(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string groupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetGroupsByName", ReplyAction="http://tempuri.org/IUserManagement/GetGroupsByNameResponse")]
        System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.Group[]> GetGroupsByNameAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string groupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetUsersInGroup", ReplyAction="http://tempuri.org/IUserManagement/GetUsersInGroupResponse")]
        System.Guid[] GetUsersInGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/GetUsersInGroup", ReplyAction="http://tempuri.org/IUserManagement/GetUsersInGroupResponse")]
        System.Threading.Tasks.Task<System.Guid[]> GetUsersInGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/SetUserHasLoggedIn", ReplyAction="http://tempuri.org/IUserManagement/SetUserHasLoggedInResponse")]
        void SetUserHasLoggedIn(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagement/SetUserHasLoggedIn", ReplyAction="http://tempuri.org/IUserManagement/SetUserHasLoggedInResponse")]
        System.Threading.Tasks.Task SetUserHasLoggedInAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagementChannel : SyllabusPlusSchedulerService.UserManagement.IUserManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagementClient : System.ServiceModel.ClientBase<SyllabusPlusSchedulerService.UserManagement.IUserManagement>, SyllabusPlusSchedulerService.UserManagement.IUserManagement {
        
        public UserManagementClient() {
        }
        
        public UserManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid CreateUser(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, SyllabusPlusSchedulerService.UserManagement.User user, string initialPassword) {
            return base.Channel.CreateUser(auth, user, initialPassword);
        }
        
        public System.Threading.Tasks.Task<System.Guid> CreateUserAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, SyllabusPlusSchedulerService.UserManagement.User user, string initialPassword) {
            return base.Channel.CreateUserAsync(auth, user, initialPassword);
        }
        
        public SyllabusPlusSchedulerService.UserManagement.User[] CreateUsers(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, SyllabusPlusSchedulerService.UserManagement.User[] users) {
            return base.Channel.CreateUsers(auth, users);
        }
        
        public System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.User[]> CreateUsersAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, SyllabusPlusSchedulerService.UserManagement.User[] users) {
            return base.Channel.CreateUsersAsync(auth, users);
        }
        
        public SyllabusPlusSchedulerService.UserManagement.User GetUserByKey(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string userKey) {
            return base.Channel.GetUserByKey(auth, userKey);
        }
        
        public System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.User> GetUserByKeyAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string userKey) {
            return base.Channel.GetUserByKeyAsync(auth, userKey);
        }
        
        public SyllabusPlusSchedulerService.UserManagement.User[] GetUsers(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid[] userIds) {
            return base.Channel.GetUsers(auth, userIds);
        }
        
        public System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.User[]> GetUsersAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid[] userIds) {
            return base.Channel.GetUsersAsync(auth, userIds);
        }
        
        public SyllabusPlusSchedulerService.UserManagement.ListUsersResponse ListUsers(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, SyllabusPlusSchedulerService.UserManagement.ListUsersRequest parameters, string searchQuery) {
            return base.Channel.ListUsers(auth, parameters, searchQuery);
        }
        
        public System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.ListUsersResponse> ListUsersAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, SyllabusPlusSchedulerService.UserManagement.ListUsersRequest parameters, string searchQuery) {
            return base.Channel.ListUsersAsync(auth, parameters, searchQuery);
        }
        
        public void UpdateContactInfo(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId, string firstName, string lastName, string email, bool sendNotifications) {
            base.Channel.UpdateContactInfo(auth, userId, firstName, lastName, email, sendNotifications);
        }
        
        public System.Threading.Tasks.Task UpdateContactInfoAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId, string firstName, string lastName, string email, bool sendNotifications) {
            return base.Channel.UpdateContactInfoAsync(auth, userId, firstName, lastName, email, sendNotifications);
        }
        
        public void UpdateUserBio(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId, string bio) {
            base.Channel.UpdateUserBio(auth, userId, bio);
        }
        
        public System.Threading.Tasks.Task UpdateUserBioAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId, string bio) {
            return base.Channel.UpdateUserBioAsync(auth, userId, bio);
        }
        
        public void UpdatePassword(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId, string newPassword) {
            base.Channel.UpdatePassword(auth, userId, newPassword);
        }
        
        public System.Threading.Tasks.Task UpdatePasswordAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId, string newPassword) {
            return base.Channel.UpdatePasswordAsync(auth, userId, newPassword);
        }
        
        public void ResetPassword(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId) {
            base.Channel.ResetPassword(auth, userId);
        }
        
        public System.Threading.Tasks.Task ResetPasswordAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId) {
            return base.Channel.ResetPasswordAsync(auth, userId);
        }
        
        public void UnlockAccount(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId) {
            base.Channel.UnlockAccount(auth, userId);
        }
        
        public System.Threading.Tasks.Task UnlockAccountAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId) {
            return base.Channel.UnlockAccountAsync(auth, userId);
        }
        
        public void SetSystemRole(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId, SyllabusPlusSchedulerService.UserManagement.SystemRole role) {
            base.Channel.SetSystemRole(auth, userId, role);
        }
        
        public System.Threading.Tasks.Task SetSystemRoleAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId, SyllabusPlusSchedulerService.UserManagement.SystemRole role) {
            return base.Channel.SetSystemRoleAsync(auth, userId, role);
        }
        
        public void DeleteUsers(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid[] userIds) {
            base.Channel.DeleteUsers(auth, userIds);
        }
        
        public System.Threading.Tasks.Task DeleteUsersAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid[] userIds) {
            return base.Channel.DeleteUsersAsync(auth, userIds);
        }
        
        public SyllabusPlusSchedulerService.UserManagement.Group CreateInternalGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string groupName, System.Guid[] memberIds) {
            return base.Channel.CreateInternalGroup(auth, groupName, memberIds);
        }
        
        public System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.Group> CreateInternalGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string groupName, System.Guid[] memberIds) {
            return base.Channel.CreateInternalGroupAsync(auth, groupName, memberIds);
        }
        
        public bool GetGroupIsPublic(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId) {
            return base.Channel.GetGroupIsPublic(auth, groupId);
        }
        
        public System.Threading.Tasks.Task<bool> GetGroupIsPublicAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId) {
            return base.Channel.GetGroupIsPublicAsync(auth, groupId);
        }
        
        public void SetGroupIsPublic(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId, bool isPublic) {
            base.Channel.SetGroupIsPublic(auth, groupId, isPublic);
        }
        
        public System.Threading.Tasks.Task SetGroupIsPublicAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId, bool isPublic) {
            return base.Channel.SetGroupIsPublicAsync(auth, groupId, isPublic);
        }
        
        public SyllabusPlusSchedulerService.UserManagement.Group CreateExternalGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string groupName, string externalProvider, string externalId, System.Guid[] memberIds) {
            return base.Channel.CreateExternalGroup(auth, groupName, externalProvider, externalId, memberIds);
        }
        
        public System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.Group> CreateExternalGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string groupName, string externalProvider, string externalId, System.Guid[] memberIds) {
            return base.Channel.CreateExternalGroupAsync(auth, groupName, externalProvider, externalId, memberIds);
        }
        
        public void AddMembersToInternalGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId, System.Guid[] memberIds) {
            base.Channel.AddMembersToInternalGroup(auth, groupId, memberIds);
        }
        
        public System.Threading.Tasks.Task AddMembersToInternalGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId, System.Guid[] memberIds) {
            return base.Channel.AddMembersToInternalGroupAsync(auth, groupId, memberIds);
        }
        
        public void RemoveMembersFromInternalGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId, System.Guid[] memberIds) {
            base.Channel.RemoveMembersFromInternalGroup(auth, groupId, memberIds);
        }
        
        public System.Threading.Tasks.Task RemoveMembersFromInternalGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId, System.Guid[] memberIds) {
            return base.Channel.RemoveMembersFromInternalGroupAsync(auth, groupId, memberIds);
        }
        
        public void AddMembersToExternalGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string externalProviderName, string externalGroupId, System.Guid[] memberIds) {
            base.Channel.AddMembersToExternalGroup(auth, externalProviderName, externalGroupId, memberIds);
        }
        
        public System.Threading.Tasks.Task AddMembersToExternalGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string externalProviderName, string externalGroupId, System.Guid[] memberIds) {
            return base.Channel.AddMembersToExternalGroupAsync(auth, externalProviderName, externalGroupId, memberIds);
        }
        
        public void RemoveMembersFromExternalGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string externalProviderName, string externalGroupId, System.Guid[] memberIds) {
            base.Channel.RemoveMembersFromExternalGroup(auth, externalProviderName, externalGroupId, memberIds);
        }
        
        public System.Threading.Tasks.Task RemoveMembersFromExternalGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string externalProviderName, string externalGroupId, System.Guid[] memberIds) {
            return base.Channel.RemoveMembersFromExternalGroupAsync(auth, externalProviderName, externalGroupId, memberIds);
        }
        
        public void SyncExternalUser(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string firstName, string lastName, string email, bool EmailSessionNotifications, string[] externalGroupIds) {
            base.Channel.SyncExternalUser(auth, firstName, lastName, email, EmailSessionNotifications, externalGroupIds);
        }
        
        public System.Threading.Tasks.Task SyncExternalUserAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string firstName, string lastName, string email, bool EmailSessionNotifications, string[] externalGroupIds) {
            return base.Channel.SyncExternalUserAsync(auth, firstName, lastName, email, EmailSessionNotifications, externalGroupIds);
        }
        
        public void DeleteGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId) {
            base.Channel.DeleteGroup(auth, groupId);
        }
        
        public System.Threading.Tasks.Task DeleteGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId) {
            return base.Channel.DeleteGroupAsync(auth, groupId);
        }
        
        public SyllabusPlusSchedulerService.UserManagement.Group GetGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId) {
            return base.Channel.GetGroup(auth, groupId);
        }
        
        public System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.Group> GetGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId) {
            return base.Channel.GetGroupAsync(auth, groupId);
        }
        
        public SyllabusPlusSchedulerService.UserManagement.ListGroupsResponse ListGroups(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, SyllabusPlusSchedulerService.UserManagement.Pagination pagination) {
            return base.Channel.ListGroups(auth, pagination);
        }
        
        public System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.ListGroupsResponse> ListGroupsAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, SyllabusPlusSchedulerService.UserManagement.Pagination pagination) {
            return base.Channel.ListGroupsAsync(auth, pagination);
        }
        
        public SyllabusPlusSchedulerService.UserManagement.Group[] GetGroupsByName(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string groupName) {
            return base.Channel.GetGroupsByName(auth, groupName);
        }
        
        public System.Threading.Tasks.Task<SyllabusPlusSchedulerService.UserManagement.Group[]> GetGroupsByNameAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, string groupName) {
            return base.Channel.GetGroupsByNameAsync(auth, groupName);
        }
        
        public System.Guid[] GetUsersInGroup(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId) {
            return base.Channel.GetUsersInGroup(auth, groupId);
        }
        
        public System.Threading.Tasks.Task<System.Guid[]> GetUsersInGroupAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid groupId) {
            return base.Channel.GetUsersInGroupAsync(auth, groupId);
        }
        
        public void SetUserHasLoggedIn(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId) {
            base.Channel.SetUserHasLoggedIn(auth, userId);
        }
        
        public System.Threading.Tasks.Task SetUserHasLoggedInAsync(SyllabusPlusSchedulerService.UserManagement.AuthenticationInfo auth, System.Guid userId) {
            return base.Channel.SetUserHasLoggedInAsync(auth, userId);
        }
    }
}
